export const ABT_API_DOMAIN = 'https://abtapp.transitlink.com.sg';
export const ABT_API_BASE = `${ABT_API_DOMAIN}/api`;
export const ABT_API_SIGN_IN = '/account/SignIn';
export const ABT_API_LOG_OUT = '/account/Logout';
export const ABT_API_GET_CARDS = '/card/getWithSharing';
export const ABT_API_GET_TRANSACTIONS = '/card/Transactions';
export const ABT_APP_ID = 'e62e7c778eed4b5ba220a8d3c512a555';
export const ABT_APP_KEY = 'hbssWNf65LyAuYomc4HQTzopBw0MPOY/llZ54mTeKNM=';
export const ABT_APP_MAGIC_HEADER = 'e62e7c778eed4b5ba220a8d3c512a555';